# Generated by Django 6.1.1 on 2026-09-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('Education', models.CharField(choices=[('Undergad', 'Undegraduate'), ('Postgrad', 'Postgraduate'), ('PhD', 'PhD / Reasearch')], default='Undergad', max_length=20)),
                ('College', models.CharField(max_length=100)),
                ('Carrer_Interest', models.CharField(choices=[('Industry', 'Industry / Job'), ('Masters', 'Masters / Postgraduate'), ('Research', 'Research / PhD'), ('Entrepreneurship', 'Entrepreneurship / Startup'), ('Other', 'Other'), ('Undecided', 'Still deciding')], default='Undecided', max_length=20)),
                ('Status', models.CharField(choices=[('Studying', 'Studying'), ('Working', 'Working'), ('Looking for opportunities', 'Looking for opportunities'), ('Taking a break', 'Taking a break'), ('Other', 'Other')], default='Studying', max_length=30)),
                ('Year_of_Study', models.IntegerField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], null=True)),
                ('Years_of_Experience', models.PositiveIntegerField(blank=True, null=True)),
                ('User_registerd', models.DateTimeField(auto_now_add=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
