# Generated by Django 6.1.1 on 2026-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('skills', '0002_studentskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_extracted_skills',
            field=models.ManyToManyField(blank=True, related_name='resumes_mentioning', to='skills.skill'),
        ),
    ]
