# Generated by Django 6.1.1 on 2026-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
