# Generated by Django 6.1.1 on 2026-09-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='analysis.skillanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analysis.skillanalysis')),
                ('skill_gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analysis.skillgap')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'Phase 1 - Strengthen Fundamentals'), (2, 'Phase 2 - Core Skills'), (3, 'Phase 3 - Advanced Skills'), (4, 'Phase 4 - Portfolio Project')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.learningroadmap')),
                ('skill_gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.skillgap')),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
    ]
